const images = [
    "dewsbury-hall.png",
    "sheaf.png",
    "clauss.png",
    "david-costa.png",
    "dest.png",
    "udol.png",
    "gabri-veiga.png",
    "nkunku.png",
    "beier.png",
    "muslera.png",
    "dreyer.png",
    "zaha.png",
    "teze.png",
    "hancko.png",
    "robinson.png",
    "otamendi.png",
    "mcginn.png",
    "loftus-cheek.png",
    "kudus.png",
    "estupinian.png",
    "cucho hernandez.png",
    "alvarez.png",
    "szoboszlai.png",
    "st.juste.png",
    "saint-maximin.png",
    "konate.png",
    "douglas-luiz.png",
    "doku.png",
    "lucas-vazquez.png",
    "fred.png",
    "walker-peters.png",
    "pavlovic.png",
    "tadic.png",
    "davis.png",
    "palacios.png",
    "acosta.png",
    "adeyemi.png",
    "smalling.png",
    "steffen.png",
    "timber.png",
    "wendell.png",
    "upamecano.png",
    "sancho.png",
    "beste.png",
    "davies.png",
    "coman.png",
    "vertonghen.png",
    "reus.png",
    "simakan.png",
    "tapsoba.png",
    "hartel.png",
    "lala.png",
    "sugawara.png",
    "minamino.png",
    "al-dawsari.png",
    "cherki.png",
    "szmodics.png",
    "pedro-goncha.png",
    "locko.png",
    "hernandez.png",
    "todibo.png",
    "zhegrova.png",
    "ruben-neves.png",
    "mbemba.png",
    "zakaria.png",
    "podolski.png",
    "firmino.png",
    "felix.png",
    "kadioglu.png",
    "bonucci.png",
    "kounde.png",
    "traore.png",
    "de-jong.png",
    "bouanga.png",
    "vivian.png",
    "neves.png",
    "summerville.png",
    "herrera.png",
    "mercan.png",
    "bennacer.png",
    "icardi.png",
    "berardi.png",
    "szc.png",
    "alba.png",
    "lorenzo.png",
    "bakayoko.png",
    "koulibaly.png",
    "nanasi.png",
    "puertas.png",
    "costinha.png",
];

const randomImage = () => {
    const randomIndex = Math.floor(Math.random() * images.length);
    const selectedImage = images[randomIndex];
    const imageElement = document.getElementById("random-image");
    imageElement.src = selectedImage;
};

const generateButton = document.getElementById("generate-btn");
generateButton.addEventListener("click", randomImage);
