const images = [
    "inaki.png",
    "kubo.png",
    "garnacho.png",
    "anton.png",
    "banza.png",
    "bentaleb.png",
    "bisseck.png",
    "brobbey.png",
    "calafiori.png",
    "camavinga.png",
    "dante.png",
    "ferguson.png",
    "goretzka.png",
    "gudmundson.png",
    "havertz.png",
    "cancelo.png",
    "lacazette.png",
    "mahrez.png",
    "medina.png",
    "merino.png",
    "milinkovic.png",
    "rafa.png",
    "mkhitaryan.png",
    "palmer.png",
    "romero.png",
    "busqets.png",
    "simons.png",
    "unai.png",
    "santos.png",
    "vanaken2.png",
    "vardy.png",
    "veerman2.png",
    "white.png",
    "aleix.png",
    "alisson.png",
    "araujo.png",
    "balotelli.png",
    "barella.png",
    "jobe.png",
    "boniface.png",
    "bowen.png",
    "bruno.png",
    "carvajal.png",
    "david.png",
    "diaz.png",
    "viktor.png",
    "golovinn.png",
    "martin.png",
    "zirkzee.png",
    "emery.png",
    "vitinha.png",
    "sorloth.png",
    "sommer.png",
    "nico.png",
    "sane.png",
    "rodrygo.png",
    "raphinha.png",
    "pulisic.png",
    "pepe.png",
    "pellegrini.png",
    "osimhen.png",
    "openda.png",
    "mendes.png",
    "willijr.png",
    "neymar.png",
    "nani.png",
    "mainoo.png",
    "robert.png",
    "kante.png",
    "hincapie.png",
    "allister.png",
];

const randomImage = () => {
    const randomIndex = Math.floor(Math.random() * images.length);
    const selectedImage = images[randomIndex];
    const imageElement = document.getElementById("random-image");
    imageElement.src = selectedImage;
};

const generateButton = document.getElementById("generate-btn");
generateButton.addEventListener("click", randomImage);